"""removing toy

Revision ID: 0da5f25c033b
Revises: 409858ebcf95
Create Date: 2023-06-16 10:40:57.489024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da5f25c033b'
down_revision = '409858ebcf95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toys')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toys',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_name', sa.TEXT(), nullable=True),
    sa.Column('pet_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
