"""THE RETURN

Revision ID: 329a90efe53c
Revises: 0da5f25c033b
Create Date: 2023-06-16 10:43:36.221462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329a90efe53c'
down_revision = '0da5f25c033b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.Text(), nullable=True),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('toys')
    # ### end Alembic commands ###
